---
- name: Download Zabbix Repositorio
  get_url: 
    url: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm 
    dest: /tmp/zabbix-release-5.0-1.el7.noarch.rpm

- name: Instalação Zabbix Repositorio
  command: rpm -ivh /tmp/zabbix-release-5.0-1.el7.noarch.rpm

- name: Instalação pacotes Zabbix
  yum:
    name:
      - zabbix-agent
      - zabbix-sender
    state: latest

- name: Start Zabbix-agent
  service: 
    name: zabbix-agent 
    state: started 
    enabled: yes
...